### ISSUE TITLE
 Not applayed some parametrs from jicofo.conf

### ISSUE THREAD

**Issue by splinehip** [jitsi/jicofo#1105]
## Description
`jicofo {
  xmpp {
    client {
      hostname = "test.local"
      port = "80"
     ......
      use-tls = false
    }
  }
}`

## Current behavior
xmpp-client not use hostname and use-tls args from jicofo.conf
`SEVERE: Failed to connect/login: The following addresses failed: 'RFC 6120 A/AAAA Endpoint + [localhost:80] (localhost/127.0.0.1:80)' failed because: java.net.ConnectException: Connection refused (Connection refused), 'RFC 6120 A/AAAA Endpoint + [localhost:80] (localhost/0:0:0:0:0:0:0:1:80)' failed because: java.net.ConnectException: Connection refused (Connection refused)
org.jivesoftware.smack.SmackException$EndpointConnectionException: The following addresses failed: 'RFC 6120 A/AAAA Endpoint + [localhost:80] (localhost/127.0.0.1:80)' failed because: java.net.ConnectException: Connection refused (Connection refused), 'RFC 6120 A/AAAA Endpoint + [localhost:80] (localhost/0:0:0:0:0:0:0:1:80)' failed because: java.net.ConnectException: Connection refused (Connection refused)
	at org.jivesoftware.smack.SmackException$EndpointConnectionException.from(SmackException.java:334)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:663)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:846)
	at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:526)
	at org.jitsi.impl.protocol.xmpp.XmppProviderImpl.doConnect(XmppProviderImpl.java:208)
	at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:167)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)`

## Expected Behavior
xmpp-client USE hostname and use-tls args from jicofo.conf

## Steps to reproduce
build single jar of jicofo 7830, run `java -Dconfig.file=jicofo.conf -jar jicofo/target/jicofo-1.1-SNAPSHOT-jar-with-dependencies.jar`

**Comment by splinehip** [comment]
Problem:
in jicofo.conf set hostname for xmpp-clien but jicofo try to connect to localhost always

**Comment by damencho** [comment]
I tested with master source code and I don't see a problem.
With your example:
```
SEVERE: Failed to connect/login: Could not lookup the following endpoints: RemoteConnectionEndpointLookupFailure(description='DNS lookup exception for test.local' exception='java.net.UnknownHostException: test.local: nodename nor servname provided, or not known')
org.jivesoftware.smack.SmackException$EndpointConnectionException: Could not lookup the following endpoints: RemoteConnectionEndpointLookupFailure(description='DNS lookup exception for test.local' exception='java.net.UnknownHostException: test.local: nodename nor servname provided, or not known')
```

Please try with latest source from master.

**Comment by splinehip** [comment]
_Please try with latest source from master._
i cant
