### ISSUE TITLE
jicofo fails to start, uncaught exception

### ISSUE THREAD

**Issue by tpearson-ssc** [jitsi/jicofo#1162]
After a source upgrade to the `stable/jitsi-meet_9646` branch, jicofo fails to start with

```
Jicofo 2024-08-07 13:51:41.683 SEVERE: [1] Main.lambda$main$0#50: An uncaught exception occurred in thread=Thread[main,5,main]
java.lang.NoSuchMethodError: 'boolean org.jitsi.jicofo.xmpp.XmppConfig.getUseJitsiJidValidation()'
        at org.jitsi.jicofo.xmpp.SmackKt.initializeSmack(Smack.kt:57)
        at org.jitsi.jicofo.JicofoServices.<init>(JicofoServices.kt:68)
        at org.jitsi.jicofo.Main.main(Main.java:72)
```

I can't find any source location where `getUseJitsiJidValidation()` is actually supposed to be defined, and Google is worse than useless.  Help? :smile:

**Comment by tpearson-ssc** [comment]
Looks like this is where the problem was introduced:

https://github.com/jitsi/jicofo/commit/62b126fe39c9fce301195d15b6f61d4be6d6b58c

Still don't know how to get this fixed though.

**Comment by tpearson-ssc** [comment]
Digging more, it seems to be a Debian packaging problem (i.e., the Debian packaging in the source tree).  After clearing out the .m2 cache directory and trying another rebuild, I get:

`[ERROR] Failed to execute goal on project jicofo-selector: Could not resolve dependencies for project org.jitsi:jicofo-selector:jar:1.1-SNAPSHOT: Could not find artifact org.jitsi:jicofo-common:jar:1.1-SNAPSHOT in jitsi-maven-repository-snapshots (https://github.com/jitsi/jitsi-maven-repository/raw/master/snapshots/) -> [Help 1]`

Now the errors above actually make sense -- it was silently using an old cached version of `jicofo-common`

**Comment by tpearson-ssc** [comment]
Got it.  The documentation needs a bit of an update -- to rebuild the Debian packages on an existing server, the `~/.m2` directory needs to be deleted, then `mvn install`, then `dpkg-buildpackage`.  Otherwise the stale `.jar`. files will be used from the previous build, leading to all kinds of problems!
