### ISSUE TITLE
Timeout for colibri endpoint allocation too small, unconfigurable

### ISSUE THREAD

**Issue by micha030201** [jitsi/jicofo#1198]
## Description

On my self-hosted setup, colibri endpoint allocation occasionally takes over 5 seconds, causing jicofo to timeout and drop the bridge. This leads to sporadic failures when starting a conference -- starting it a second or third time sometimes fixes the issue if the colibri endpoint is allocated quickly enough.

## Current behavior

<details>
<summary>Relevant part of the jicofo log</summary>

```
Jicofo 2024-12-04 12:17:18.808 SEVERE: [130] [room=roomname@conference.redacted.domain meeting_id=d4e34611-0d36-4f51-94cb-09478a70abd4] ColibriV2SessionManager.allocate#397: Failed to allocate a colibri2 endpoint for d01221d8: Timeout
Jicofo 2024-12-04 12:17:20.188 INFO: [131] [room=roomname@conference.redacted.domain meeting_id=d4e34611-0d36-4f51-94cb-09478a70abd4] ColibriV2SessionManager.allocate#378: Ignoring response for a session that's no longer active (bridge=jvbbrewery@internal.auth.redacted.domain/157354f3-2348-498b-bc9b-e0bd05258b5b)
Jicofo 2024-12-04 12:17:20.214 SEVERE: [131] [room=roomname@conference.redacted.domain meeting_id=d4e34611-0d36-4f51-94cb-09478a70abd4 participant=6a63fefa] ParticipantInviteRunnable.doRun#230: Failed to allocate colibri channels
org.jitsi.jicofo.bridge.colibri.ColibriAllocationFailedException: Session no longer active (bridge=jvbbrewery@internal.auth.redacted.domain/157354f3-2348-498b-bc9b-e0bd05258b5b)
        at org.jitsi.jicofo.bridge.colibri.ColibriV2SessionManager.allocate(ColibriV2SessionManager.kt:379)
        at org.jitsi.jicofo.conference.ParticipantInviteRunnable.doRun(ParticipantInviteRunnable.java:214)
        at org.jitsi.jicofo.conference.ParticipantInviteRunnable.run(ParticipantInviteRunnable.java:153)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
Jicofo 2024-12-04 12:17:20.803 INFO: [128] [room=roomname@conference.redacted.domain meeting_id=d4e34611-0d36-4f51-94cb-09478a70abd4] JitsiMeetConferenceImpl$ColibriSessionManagerListener.bridgeRemoved#2513: Bridge Bridge[jid=jvbbrewery@internal.auth.redacted.domain/157354f3-2348-498b-bc9b-e0bd05258b5b, version=2.3.168-g28674f78, relayId=null, region=null, stress=0.02] was removed from the conference. Re-inviting its participants: [d01221d8, 6a63fefa]
Jicofo 2024-12-04 12:17:20.823 SEVERE: [130] [room=roomname@conference.redacted.domain meeting_id=d4e34611-0d36-4f51-94cb-09478a70abd4 participant=d01221d8] ParticipantInviteRunnable.doRun#230: Failed to allocate colibri channels
org.jitsi.jicofo.bridge.colibri.ColibriAllocationFailedException: Timeout
        at org.jitsi.jicofo.bridge.colibri.ColibriV2SessionManager.handleResponse(ColibriV2SessionManager.kt:436)
        at org.jitsi.jicofo.bridge.colibri.ColibriV2SessionManager.allocate(ColibriV2SessionManager.kt:392)
        at org.jitsi.jicofo.conference.ParticipantInviteRunnable.doRun(ParticipantInviteRunnable.java:214)
        at org.jitsi.jicofo.conference.ParticipantInviteRunnable.run(ParticipantInviteRunnable.java:153)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
Jicofo 2024-12-04 12:17:21.452 INFO: [131] [room=roomname@conference.redacted.domain meeting_id=d4e34611-0d36-4f51-94cb-09478a70abd4] ColibriV2SessionManager.allocate#281: Allocating for 6a63fefa
Jicofo 2024-12-04 12:17:21.453 INFO: [130] [room=roomname@conference.redacted.domain meeting_id=d4e34611-0d36-4f51-94cb-09478a70abd4] ColibriV2SessionManager.allocate#281: Allocating for d01221d8
Jicofo 2024-12-04 12:17:21.507 WARNING: [131] BridgeSelector.selectBridge#182: There are no operational bridges.
Jicofo 2024-12-04 12:17:21.538 WARNING: [130] BridgeSelector.selectBridge#182: There are no operational bridges.
Jicofo 2024-12-04 12:17:21.539 SEVERE: [131] [room=roomname@conference.redacted.domain meeting_id=d4e34611-0d36-4f51-94cb-09478a70abd4 participant=6a63fefa] ParticipantInviteRunnable.doRun#218: Can not invite participant, no bridge available.
Jicofo 2024-12-04 12:17:21.576 SEVERE: [130] [room=roomname@conference.redacted.domain meeting_id=d4e34611-0d36-4f51-94cb-09478a70abd4 participant=d01221d8] ParticipantInviteRunnable.doRun#218: Can not invite participant, no bridge available.
```

(room name, domain, and external IP address redacted to `roomname`, `redacted.domain` and `123.123.123.123` respectively)

</details>

<details>
<summary>Corresponding part of the JVB log</summary>

```
JVB 2024-12-04 12:17:06.655 INFO: [5203] Videobridge.createConference#213: create_conf, id=bec0144cee5be4a0 meeting_id=d4e34611-0d36-4f51-94cb-09478a70abd4
JVB 2024-12-04 12:17:12.894 INFO: [5206] [confId=bec0144cee5be4a0 conf_name=roomname@conference.redacted.domain meeting_id=d4e34611] Conference.lambda$new$1#227: RECV colibri2 request: <iq xmlns="jabber:client" to="jvb@auth.redacted.domain/0X-W8fniNZwH" from="jvbbrewery@internal.auth.redacted.domain/focus" id="anZiQGF1dGguaml0c2kuZWxlcmdhcmQucG9sYXJvcmJpdC5zcGFjZS8wWC1XOGZuaU5ad0gAOVdVMVgtMTQ1AIXVxt8+ZalJ" type="get"><conference-modify xmlns="jitsi:colibri2" meeting-id="d4e34611-0d36-4f51-94cb-09478a70abd4" name="roomname@conference.redacted.domain" rtcstats-enabled="false" create="true"><endpoint create="true" stats-id="Lea-UrM" id="d01221d8"><media type="audio"><payload-type xmlns="urn:xmpp:jingle:apps:rtp:1" channels="2" id="111" name="opus" clockrate="48000"><parameter name="minptime" value="10"/><parameter name="useinbandfec" value="1"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" type="transport-cc"/></payload-type><payload-type xmlns="urn:xmpp:jingle:apps:rtp:1" name="telephone-event" clockrate="8000" id="126"/><rtp-hdrext xmlns="urn:xmpp:jingle:apps:rtp:rtp-hdrext:0" uri="urn:ietf:params:rtp-hdrext:ssrc-audio-level" id="1"/><rtp-hdrext xmlns="urn:xmpp:jingle:apps:rtp:rtp-hdrext:0" uri="http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01" id="5"/><extmap-allow-mixed xmlns="urn:xmpp:jingle:apps:rtp:rtp-hdrext:0"/></media><media type="video"><payload-type xmlns="urn:xmpp:jingle:apps:rtp:1" name="AV1" clockrate="90000" id="41"><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" subtype="fir" type="ccm"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" type="nack"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" subtype="pli" type="nack"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" type="transport-cc"/></payload-type><payload-type xmlns="urn:xmpp:jingle:apps:rtp:1" name="VP8" clockrate="90000" id="100"><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" subtype="fir" type="ccm"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" type="nack"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" subtype="pli" type="nack"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" type="transport-cc"/></payload-type><payload-type xmlns="urn:xmpp:jingle:apps:rtp:1" name="H264" clockrate="90000" id="107"><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" subtype="fir" type="ccm"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" type="nack"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" subtype="pli" type="nack"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" type="transport-cc"/><parameter name="profile-level-id" value="42e01f;level-asymmetry-allowed=1;packetization-mode=1;"/></payload-type><payload-type xmlns="urn:xmpp:jingle:apps:rtp:1" name="VP9" clockrate="90000" id="101"><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" subtype="fir" type="ccm"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" type="nack"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" subtype="pli" type="nack"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" type="transport-cc"/></payload-type><payload-type xmlns="urn:xmpp:jingle:apps:rtp:1" name="rtx" clockrate="90000" id="42"><parameter name="apt" value="41"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" subtype="fir" type="ccm"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" type="nack"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" subtype="pli" type="nack"/></payload-type><payload-type xmlns="urn:xmpp:jingle:apps:rtp:1" name="rtx" clockrate="90000" id="96"><parameter name="apt" value="100"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" subtype="fir" type="ccm"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" type="nack"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" subtype="pli" type="nack"/></payload-type><payload-type xmlns="urn:xmpp:jingle:apps:rtp:1" name="rtx" clockrate="90000" id="97"><parameter name="apt" value="101"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" subtype="fir" type="ccm"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" type="nack"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" subtype="pli" type="nack"/></payload-type><payload-type xmlns="urn:xmpp:jingle:apps:rtp:1" name="rtx" clockrate="90000" id="99"><parameter name="apt" value="107"/></payload-type><rtp-hdrext xmlns="urn:xmpp:jingle:apps:rtp:rtp-hdrext:0" uri="https://aomediacodec.github.io/av1-rtp-spec/#dependency-descriptor-rtp-header-extension" id="11"/><rtp-hdrext xmlns="urn:xmpp:jingle:apps:rtp:rtp-hdrext:0" uri="http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time" id="3"/><rtp-hdrext xmlns="urn:xmpp:jingle:apps:rtp:rtp-hdrext:0" uri="http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01" id="5"/><extmap-allow-mixed xmlns="urn:xmpp:jingle:apps:rtp:rtp-hdrext:0"/></media><transport ice-controlling="true"><sctp/></transport><sources/><capability name="source-names"/><capability name="ssrc-rewriting"/></endpoint></conference-modify></iq>
JVB 2024-12-04 12:17:14.256 INFO: [5206] [confId=bec0144cee5be4a0 conf_name=roomname@conference.redacted.domain meeting_id=d4e34611 epId=d01221d8 local_ufrag=67ikt1ie8pko6u ufrag=67ikt1ie8pko6u] Agent.gatherCandidates#637: Gathering candidates for component stream.RTP.
JVB 2024-12-04 12:17:16.313 INFO: [5206] [confId=bec0144cee5be4a0 conf_name=roomname@conference.redacted.domain meeting_id=d4e34611 epId=d01221d8] Endpoint.<init>#386: Created new endpoint, iceControlling=true
JVB 2024-12-04 12:17:17.875 WARNING: [5206] [confId=bec0144cee5be4a0 conf_name=roomname@conference.redacted.domain meeting_id=d4e34611] Conference.lambda$new$1#251: Took 4865 ms to process an IQ (total delay 13620 ms): <iq xmlns="jabber:client" to="jvb@auth.redacted.domain/0X-W8fniNZwH" from="jvbbrewery@internal.auth.redacted.domain/focus" id="anZiQGF1dGguaml0c2kuZWxlcmdhcmQucG9sYXJvcmJpdC5zcGFjZS8wWC1XOGZuaU5ad0gAOVdVMVgtMTQ1AIXVxt8+ZalJ" type="get"><conference-modify xmlns="jitsi:colibri2" meeting-id="d4e34611-0d36-4f51-94cb-09478a70abd4" name="roomname@conference.redacted.domain" rtcstats-enabled="false" create="true"><endpoint create="true" stats-id="Lea-UrM" id="d01221d8"><media type="audio"><payload-type xmlns="urn:xmpp:jingle:apps:rtp:1" channels="2" id="111" name="opus" clockrate="48000"><parameter name="minptime" value="10"/><parameter name="useinbandfec" value="1"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" type="transport-cc"/></payload-type><payload-type xmlns="urn:xmpp:jingle:apps:rtp:1" name="telephone-event" clockrate="8000" id="126"/><rtp-hdrext xmlns="urn:xmpp:jingle:apps:rtp:rtp-hdrext:0" uri="urn:ietf:params:rtp-hdrext:ssrc-audio-level" id="1"/><rtp-hdrext xmlns="urn:xmpp:jingle:apps:rtp:rtp-hdrext:0" uri="http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01" id="5"/><extmap-allow-mixed xmlns="urn:xmpp:jingle:apps:rtp:rtp-hdrext:0"/></media><media type="video"><payload-type xmlns="urn:xmpp:jingle:apps:rtp:1" name="AV1" clockrate="90000" id="41"><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" subtype="fir" type="ccm"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" type="nack"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" subtype="pli" type="nack"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" type="transport-cc"/></payload-type><payload-type xmlns="urn:xmpp:jingle:apps:rtp:1" name="VP8" clockrate="90000" id="100"><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" subtype="fir" type="ccm"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" type="nack"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" subtype="pli" type="nack"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" type="transport-cc"/></payload-type><payload-type xmlns="urn:xmpp:jingle:apps:rtp:1" name="H264" clockrate="90000" id="107"><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" subtype="fir" type="ccm"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" type="nack"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" subtype="pli" type="nack"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" type="transport-cc"/><parameter name="profile-level-id" value="42e01f;level-asymmetry-allowed=1;packetization-mode=1;"/></payload-type><payload-type xmlns="urn:xmpp:jingle:apps:rtp:1" name="VP9" clockrate="90000" id="101"><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" subtype="fir" type="ccm"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" type="nack"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" subtype="pli" type="nack"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" type="transport-cc"/></payload-type><payload-type xmlns="urn:xmpp:jingle:apps:rtp:1" name="rtx" clockrate="90000" id="42"><parameter name="apt" value="41"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" subtype="fir" type="ccm"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" type="nack"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" subtype="pli" type="nack"/></payload-type><payload-type xmlns="urn:xmpp:jingle:apps:rtp:1" name="rtx" clockrate="90000" id="96"><parameter name="apt" value="100"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" subtype="fir" type="ccm"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" type="nack"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" subtype="pli" type="nack"/></payload-type><payload-type xmlns="urn:xmpp:jingle:apps:rtp:1" name="rtx" clockrate="90000" id="97"><parameter name="apt" value="101"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" subtype="fir" type="ccm"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" type="nack"/><rtcp-fb xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" subtype="pli" type="nack"/></payload-type><payload-type xmlns="urn:xmpp:jingle:apps:rtp:1" name="rtx" clockrate="90000" id="99"><parameter name="apt" value="107"/></payload-type><rtp-hdrext xmlns="urn:xmpp:jingle:apps:rtp:rtp-hdrext:0" uri="https://aomediacodec.github.io/av1-rtp-spec/#dependency-descriptor-rtp-header-extension" id="11"/><rtp-hdrext xmlns="urn:xmpp:jingle:apps:rtp:rtp-hdrext:0" uri="http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time" id="3"/><rtp-hdrext xmlns="urn:xmpp:jingle:apps:rtp:rtp-hdrext:0" uri="http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01" id="5"/><extmap-allow-mixed xmlns="urn:xmpp:jingle:apps:rtp:rtp-hdrext:0"/></media><transport ice-controlling="true"><sctp/></transport><sources/><capability name="source-names"/><capability name="ssrc-rewriting"/></endpoint></conference-modify></iq>
JVB 2024-12-04 12:17:17.896 INFO: [5206] [confId=bec0144cee5be4a0 conf_name=roomname@conference.redacted.domain meeting_id=d4e34611] Conference.lambda$new$1#254: SENT colibri2 response: <iq xmlns='jabber:client' to='jvbbrewery@internal.auth.redacted.domain/focus' from='jvb@auth.redacted.domain/0X-W8fniNZwH' id='anZiQGF1dGguaml0c2kuZWxlcmdhcmQucG9sYXJvcmJpdC5zcGFjZS8wWC1XOGZuaU5ad0gAOVdVMVgtMTQ1AIXVxt8+ZalJ' type='result'><conference-modified xmlns='jitsi:colibri2'><endpoint id='d01221d8'><transport><transport xmlns='urn:xmpp:jingle:transports:ice-udp:1' pwd='10vt4nu4jfm8raehg79o61fcpm' ufrag='67ikt1ie8pko6u'><rtcp-mux/><fingerprint xmlns='urn:xmpp:jingle:apps:dtls:0' setup='actpass' hash='sha-256'>9D:9F:06:0E:D6:15:DC:F3:68:7A:FD:03:C4:46:85:69:F4:34:DF:2B:36:9D:DB:19:EA:78:2B:5F:A0:E4:25:F6</fingerprint><web-socket xmlns='http://jitsi.org/protocol/colibri' url='wss://redacted.domain:443/colibri-ws/default-id/bec0144cee5be4a0/d01221d8?pwd=10vt4nu4jfm8raehg79o61fcpm'/><candidate component='1' foundation='1' generation='0' id='44105b224cf87ac90ffffffff8764a19b' network='0' priority='2130706431' protocol='udp' type='host' ip='10.11.0.2' port='10000'/><candidate component='1' foundation='2' generation='0' id='78204e484cf87ac90ffffffff8761a19a' network='0' priority='2130706431' protocol='udp' type='host' ip='10.8.0.1' port='10000'/><candidate component='1' foundation='3' generation='0' id='24bf94944cf87ac903e01c177' network='0' priority='2113932031' protocol='udp' type='host' ip='192.168.31.222' port='10000'/><candidate component='1' foundation='4' generation='0' id='6230126a4cf87ac90ffffffffdcf3f9e0' network='0' priority='1677724415' protocol='udp' type='srflx' ip='123.123.123.123' port='10000' rel-addr='192.168.31.222' rel-port='10000'/></transport><sctp role='server' port='5000'/></transport></endpoint><sources><media-source type='audio' id='jvb-a0'><source xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' ssrc='3973680167' name='jvb-a0'/></media-source><media-source type='video' id='jvb-v0'><source xmlns='urn:xmpp:jingle:apps:rtp:ssma:0' ssrc='3263014397' name='jvb-v0'/></media-source></sources></conference-modified></iq>
```

(room name, domain, and external IP address redacted to `roomname`, `redacted.domain` and `123.123.123.123` respectively)

</details>

As you can see, colibri endpoint allocation takes too long, so jicofo gives up waiting for it. After that, it removes the bridge from the meeting, and because this is the only bridge that I have, the meeting dies and has to be restarted.

## Expected Behavior

I would like to adjust the timeout in jicofo so that it doesn't give up waiting for the colibri endpoint too early.

## Possible Solution

The part that waits for the allocation request is here: https://github.com/jitsi/jicofo/blob/dd2d778e6626bb8cc8964738fc3cbb6e2065187f/jicofo-selector/src/main/kotlin/org/jitsi/jicofo/bridge/colibri/ColibriV2SessionManager.kt#L368

`stanzaCollector` gets created earlier: https://github.com/jitsi/jicofo/blob/dd2d778e6626bb8cc8964738fc3cbb6e2065187f/jicofo-selector/src/main/kotlin/org/jitsi/jicofo/bridge/colibri/ColibriV2SessionManager.kt#L338

Here is the function that does that: https://github.com/jitsi/jicofo/blob/dd2d778e6626bb8cc8964738fc3cbb6e2065187f/jicofo-selector/src/main/kotlin/org/jitsi/jicofo/bridge/colibri/Colibri2Session.kt#L89-L117

The `nextResult` function is documented [here](https://download.igniterealtime.org/smack/docs/latest/javadoc/org/jivesoftware/smack/StanzaCollector.html#nextResult()). It uses the default connection (`AbstractXMPPConnection`) timeout that is initialized [through `SmackConfiguration`](https://download.igniterealtime.org/smack/docs/latest/javadoc/src-html/org/jivesoftware/smack/AbstractXMPPConnection.html#line.246) to be [5 seconds](https://download.igniterealtime.org/smack/docs/latest/javadoc/org/jivesoftware/smack/SmackConfiguration.html#getDefaultReplyTimeout()). A timeout of 5 seconds is roughly consistent with what I am observing in the logs.

The way to change it is to either call [`nextResult` with a `timeout` parameter](https://download.igniterealtime.org/smack/docs/latest/javadoc/org/jivesoftware/smack/StanzaCollector.html#nextResult(long)) or to [`setReplyTimeout` on the `xmppConnection` object](https://download.igniterealtime.org/smack/docs/latest/javadoc/org/jivesoftware/smack/AbstractXMPPConnection.html#setReplyTimeout(long)), neither of which jicofo currently does.

There seems to be a config option for it, but apparently it is not used in this case: https://github.com/jitsi/jicofo/blob/fb29dc88dd787353c1d994f66c8aea85caa12960/jicofo-selector/src/main/resources/reference.conf#L405-L406

I may have missed something in the analysys above, in which case I apologize -- I have only taken a cursory look and I don't use Java/Kotlin much.

The best solution to me appears to be to `setReplyTimeout` on [`xmppConnection` in `ColibriV2SessionManager`](https://github.com/jitsi/jicofo/blob/dd2d778e6626bb8cc8964738fc3cbb6e2065187f/jicofo-selector/src/main/kotlin/org/jitsi/jicofo/bridge/colibri/ColibriV2SessionManager.kt#L62) with the timeout value from the config, but maybe I am missing some system design details here.

## Steps to reproduce

I honestly don't know what causes the endpoint allocation to be slow -- I noticed that the colibri reply lists all of the server's IP addresses, so it may be because my server has multiple of them (I'm doing VPN shenanigans), or just because it hits some sort of IO bottleneck (I'm running off of an HDD). If you want to reproduce it, adding `sleep(5000)` in the part of JVB (?) that creates the colibri endpoint should probably do it. I don't know where that part of code is.

# Environment details

I followed the [Self-Hosting Guide - Debian/Ubuntu server](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart/) on Debian Bookworm.

**Comment by bgrozev** [comment]
Hey @micha030201 , sorry I didn't see this sooner. Jicofo sets the reply timeout for the XmppConnection [here](https://github.com/jitsi/jicofo/blob/5803269e775b84aa53d18cade50e81c33a26cc47/jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/XmppProvider.kt#L255), and you should see it in the logs. I'll try to repro and figure out why you're seeing a 5s timeout instead when I have some time.

But the processing on the JVB side shouldn't take anywhere near 5 seconds. Does this only happen the first time you start a conference? We had some things that were being initialized on the first conference, but I thought we moved them all to the process startup. Can you enable debug logs on the JVB and see if there's any clues for which steps are taking a long time?

**Comment by micha030201** [comment]
Thank you very much for your reply!

> Jicofo sets the reply timeout for the XmppConnection [here](https://github.com/jitsi/jicofo/blob/5803269e775b84aa53d18cade50e81c33a26cc47/jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/XmppProvider.kt#L255), and you should see it in the logs. I'll try to repro and figure out why you're seeing a 5s timeout instead when I have some time.

Whoops, completely missed where the connection is initialized, my apologies. I do indeed see that line in the logs at startup:
```
Jicofo 2025-01-07 16:10:12.731 INFO: [18] [xmpp_connection=client] XmppProvider.fireRegistrationStateChanged#256: Set replyTimeout=PT15S
```
which I think is correct. Strange that I was observing it timing out quicker than 15 seconds. Not sure how to debug that further without building jicofo and JVB myself which I'm not quite too eager to do yet.

> But the processing on the JVB side shouldn't take anywhere near 5 seconds. Does this only happen the first time you start a conference? We had some things that were being initialized on the first conference, but I thought we moved them all to the process startup. Can you enable debug logs on the JVB and see if there's any clues for which steps are taking a long time?

First time after restarting JVB, you mean? I don't think so, unless I'm mistaken it had happened on subsequent conferences as well, but usually only after a long break. As in, we would start a conference once every weekend (without touching the server during the week), and the first time it would fail, but immediately trying to start it again would usually work. Could be something completely unrelated for all I know, maybe the JVB process got swapped to disk, or DNS caches expired, or something.

I have enabled debug logs on JVB, will see if I can catch the issue again, as I seem to be unable to reproduce it manually. I have also updated to the latest version in the repositories (which came out after I opened the issue).

**Comment by bgrozev** [comment]
I confirmed that the default timeout is 15 seconds and that the config option changes it as expected. Going back to your report, I can't confirm that the timeout you see is 5 seconds. Is it possible that the response took more than 15 seconds? I see that it took about 5 seconds for the bridge to handle the request once received, but the time from request being sent to response being received could have been longer. You can check earlier in jicofo's log to see when the request was sent (look for "Allocating for <ENDPOINT_ID>").

I'm closing this for now, please re-open if necessary.
