### ISSUE TITLE
jicofo.xmpp.FocusComponent.handleIQSet NullPointerException

### ISSUE THREAD

**Issue by matclab** [jitsi/jicofo#128]
I'm unable to connect as jitsi-meet says "focus.xxx.… is not available, trying again in 2 szconds".

The jifoco log file shows the following trace:
```
Jicofo 2016-09-19 14:06:06.503 SEVERE: [149] org.jitsi.jicofo.xmpp.FocusComponent.handleIQSet().340 java.lang.NullPointerException
java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.hash(ConcurrentHashMap.java:333)
        at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:988)
        at org.jitsi.jicofo.auth.AbstractAuthAuthority.getSession(AbstractAuthAuthority.java:290)
        at org.jitsi.jicofo.auth.XMPPDomainAuthAuthority.processAuthLocked(XMPPDomainAuthAuthority.java:86)
        at org.jitsi.jicofo.auth.AbstractAuthAuthority.processAuthentication(AbstractAuthAuthority.java:415)
        at org.jitsi.jicofo.xmpp.FocusComponent.processExtensions(FocusComponent.java:368)
        at org.jitsi.jicofo.xmpp.FocusComponent.handleConferenceIq(FocusComponent.java:429)
        at org.jitsi.jicofo.xmpp.FocusComponent.handleIQSet(FocusComponent.java:274)
        at org.xmpp.component.AbstractComponent.processIQRequest(AbstractComponent.java:515)
        at org.xmpp.component.AbstractComponent.processIQ(AbstractComponent.java:289)
        at org.xmpp.component.AbstractComponent.processQueuedPacket(AbstractComponent.java:239)
        at org.xmpp.component.AbstractComponent.access$100(AbstractComponent.java:81)
        at org.xmpp.component.AbstractComponent$PacketProcessor.run(AbstractComponent.java:1051)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Jicofo 2016-09-19 14:06:06.504 WARNING: [149] org.jitsi.jicofo.xmpp.FocusComponent.processIQ() (serving component 'Jitsi Meet Focus') Unexpected exception while processing IQ stanza: <iq type="set" to="focus.example.fr" from="192bfaaa-fcc9-4e89-b2e0-43fa4fce8744@guest.example.fr/39f81d04-a9e4-44ab-b8cf-3887e0c2c2c7" id="688bafe0-87d2-4280-91f6-e7faf367573c:sendIQ"><conference xmlns="http://jitsi.org/protocol/focus" room="perfectwormsjokegrimly@conference.example.fr" machine-uid="2363a378543129e36b01bf050861ec3b"><property value="-1" name="channelLastN"/><property value="false" name="adaptiveLastN"/><property value="true" name="disableRtx"/><property value="true" name="enableLipSync"/><property value="true" name="openSctp"/><property value="rewriting" name="simulcastMode"/></conference></iq>
java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.hash(ConcurrentHashMap.java:333)
        at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:988)
        at org.jitsi.jicofo.auth.AbstractAuthAuthority.getSession(AbstractAuthAuthority.java:290)
        at org.jitsi.jicofo.auth.XMPPDomainAuthAuthority.processAuthLocked(XMPPDomainAuthAuthority.java:86)
        at org.jitsi.jicofo.auth.AbstractAuthAuthority.processAuthentication(AbstractAuthAuthority.java:415)
        at org.jitsi.jicofo.xmpp.FocusComponent.processExtensions(FocusComponent.java:368)
        at org.jitsi.jicofo.xmpp.FocusComponent.handleConferenceIq(FocusComponent.java:429)
        at org.jitsi.jicofo.xmpp.FocusComponent.handleIQSet(FocusComponent.java:274)
        at org.xmpp.component.AbstractComponent.processIQRequest(AbstractComponent.java:515)
        at org.xmpp.component.AbstractComponent.processIQ(AbstractComponent.java:289)
        at org.xmpp.component.AbstractComponent.processQueuedPacket(AbstractComponent.java:239)
        at org.xmpp.component.AbstractComponent.access$100(AbstractComponent.java:81)
        at org.xmpp.component.AbstractComponent$PacketProcessor.run(AbstractComponent.java:1051)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by matclab** [comment]
Observed with jicofo  1.0-292-1 on debian 8

**Comment by paweldomas** [comment]
Please update, it was fixed in: https://github.com/jitsi/jicofo/pull/126
