### ISSUE TITLE
Forgetting to pass --user_domain leads to a NPE

### ISSUE THREAD

**Issue by linkmauve** [jitsi/jicofo#160]
Here is the stack trace:
```
Exception in thread "main" java.lang.NullPointerException
        at java.util.Hashtable.put(Hashtable.java:459)
        at java.util.Properties.setProperty(Properties.java:166)
        at java.lang.System.setProperty(System.java:796)
        at org.jitsi.jicofo.Main.main(Main.java:166)
```

**Comment by bgrozev** [comment]
Outdated
