### ISSUE TITLE
Health check failed on: jitsi-videobridge(Too many open files)

### ISSUE THREAD

**Issue by kingaceck** [jitsi/jicofo#167]
I use jicofo in jitsi-meet.But I  get error bellow an random when the service is up and running on
idle for a few days.After run the command of "/etc/init.d/jicofo restart" it working order again :

Jicofo 2017-02-13 16:40:05.754 WARNING: [96] org.jitsi.jicofo.JvbDoctor.log() Health check failed on: jitsi-videobridge.129.1.5.161 error: <error code="500" type="WAIT"><internal-server-error xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/><text xml:lang="en" xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">java.net.SocketException: Too many open files (Error creating socket)</text></error>
Jicofo 2017-02-13 16:40:05.756 INFO: [55] org.jitsi.jicofo.BridgeSelector.removeJvbAddress().192 Removing JVB: jitsi-videobridge.129.1.5.161
Jicofo 2017-02-13 16:40:05.756 INFO: [55] org.jitsi.jicofo.JvbDoctor.log() Stopping health-check task for: jitsi-videobridge.129.1.5.161

When start a jitsi meeting it fails and get exception bellow:
Jicofo 2017-02-14 08:14:41.574 SEVERE: [91] org.jitsi.jicofo.ChannelAllocator.log() Failed to allocate channels for a@conference.129.1.5.161/e7040df2
net.java.sip.communicator.service.protocol.OperationFailedException: Failed to allocate channels - no bridge configured
	at org.jitsi.jicofo.ChannelAllocator.allocateChannels(ChannelAllocator.java:372)
	at org.jitsi.jicofo.ChannelAllocator.createOffer(ChannelAllocator.java:307)
	at org.jitsi.jicofo.ChannelAllocator.discoverFeaturesAndInvite(ChannelAllocator.java:166)
	at org.jitsi.jicofo.ChannelAllocator.run(ChannelAllocator.java:135)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[jicofo-log.zip](https://github.com/jitsi/jicofo/files/772942/jicofo-log.zip)

**Comment by saghul** [comment]
What versions are you running?

**Comment by kingaceck** [comment]
jicofo_1.0-328-1_amd64.deb

Thank you



kingaceck@163.com
 
From: Saúl Ibarra Corretgé
Date: 2017-02-14 16:36
To: jitsi/jicofo
CC: kingaceck; Author
Subject: Re: [jitsi/jicofo] Health check failed on: jitsi-videobridge(Too many open files) (#167)
What versions are you running?

**Comment by damencho** [comment]
This is not a jicofo problem, so we can close this one. 

The problem comes from jvb and we had spotted this several times, tried to address it in https://github.com/jitsi/ice4j/commit/7c63d5202c3ab453028eefa2a6f81cd2f1f70ca3
and this is available in jitsi-videobridge 882. 
For more info: 
https://github.com/jitsi/jitsi-meet/issues/664 
https://github.com/jitsi/jitsi-videobridge/issues/245
https://github.com/jitsi/jitsi-meet/issues/798

Can you check the jvb version please?
