### ISSUE TITLE
Bridge selector fails on 371

### ISSUE THREAD

**Issue by webintoit** [jitsi/jicofo#228]
```bash
Jicofo 2017-09-21 14:50:18.742 SEVERE: [10] org.jitsi.jicofo.BridgeSelector.createBridgeSelectionStrategy().206 Failed to instantiate org.jitsi.jicofo.BridgeSelector$SingleBridgeSelectionStrategy. Falling back to SingleBridgeSelectionStrategy.
media_focus.1.55249q6eaf1t@proficonf5    | java.lang.IllegalAccessException: Class org.jitsi.jicofo.BridgeSelector can not access a member of class org.jitsi.jicofo.BridgeSelector$SingleBridgeSelectionStrategy with modifiers "private"
media_focus.1.55249q6eaf1t@proficonf5    | 	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:110)
media_focus.1.55249q6eaf1t@proficonf5    | 	at java.lang.Class.newInstance(Class.java:377)
media_focus.1.55249q6eaf1t@proficonf5    | 	at org.jitsi.jicofo.BridgeSelector.createBridgeSelectionStrategy(BridgeSelector.java:202)
media_focus.1.55249q6eaf1t@proficonf5    | 	at org.jitsi.jicofo.BridgeSelector.<init>(BridgeSelector.java:167)
media_focus.1.55249q6eaf1t@proficonf5    | 	at org.jitsi.jicofo.JitsiMeetServices.<init>(JitsiMeetServices.java:190)
media_focus.1.55249q6eaf1t@proficonf5    | 	at org.jitsi.jicofo.FocusManager.start(FocusManager.java:220)
media_focus.1.55249q6eaf1t@proficonf5    | 	at org.jitsi.jicofo.FocusBundleActivator.start(FocusBundleActivator.java:113)
media_focus.1.55249q6eaf1t@proficonf5    | 	at org.jitsi.impl.osgi.framework.BundleImpl.start(BundleImpl.java:293)
media_focus.1.55249q6eaf1t@proficonf5    | 	at org.jitsi.impl.osgi.framework.launch.FrameworkImpl.startLevelChanged(FrameworkImpl.java:460)
media_focus.1.55249q6eaf1t@proficonf5    | 	at org.jitsi.impl.osgi.framework.startlevel.FrameworkStartLevelImpl$Command.run(FrameworkStartLevelImpl.java:126)
media_focus.1.55249q6eaf1t@proficonf5    | 	at org.jitsi.impl.osgi.framework.AsyncExecutor.runInThread(AsyncExecutor.java:111)
media_focus.1.55249q6eaf1t@proficonf5    | 	at org.jitsi.impl.osgi.framework.AsyncExecutor.access$000(AsyncExecutor.java:17)
media_focus.1.55249q6eaf1t@proficonf5    | 	at org.jitsi.impl.osgi.framework.AsyncExecutor$1.run(AsyncExecutor.java:220)
media_focus.1.55249q6eaf1t@proficonf5    | Jicofo 2017-09-21 14:50:18.743 INFO: [10] org.jitsi.jicofo.BridgeSelector.<init>().169 Using org.jitsi.jicofo.BridgeSelector$SingleBridgeSelectionStrategy

```

**Comment by webintoit** [comment]
` Region info, conference=ff68ee: [[europe_gr_frankfurt, europe_gr_frankfurt]] `

In 365 build, bridge selection works great.

**Comment by paweldomas** [comment]
Thanks for the report ! We're looking into this.

**Comment by bgrozev** [comment]
Thanks for the report! This is harmless, as it defaults to the correct implementation, so you can safely just ignore it. I'll make a fix when I get a chance.

**Comment by webintoit** [comment]
Thank you guys!
