### ISSUE TITLE
Jicofo crashes occasionally saying "Focus must be an owner"

### ISSUE THREAD

**Issue by paweldomas** [jitsi/jicofo#24]
2015-08-25 14:00:48.331 SEVERE: [25] org.jitsi.jicofo.ChatRoomRoleAndPresence.verifyFocusRole().299 Focus must be an owner!
2015-08-25 14:00:48.339 INFO: [43] org.jitsi.jicofo.FocusManager.createConference().312 Exception while trying to start the conference
net.java.sip.communicator.service.protocol.OperationFailedException: Failed to join the room
        at org.jitsi.impl.protocol.xmpp.ChatRoomImpl.joinAs(ChatRoomImpl.java:235)
        at org.jitsi.impl.protocol.xmpp.ChatRoomImpl.join(ChatRoomImpl.java:156)
        at org.jitsi.jicofo.JitsiMeetConference.joinTheRoom(JitsiMeetConference.java:308)
        at org.jitsi.jicofo.JitsiMeetConference.start(JitsiMeetConference.java:277)
        at org.jitsi.jicofo.FocusManager.createConference(FocusManager.java:308)
        at org.jitsi.jicofo.FocusManager.conferenceRequest(FocusManager.java:244)
        at org.jitsi.jicofo.xmpp.FocusComponent.handleConferenceIq(FocusComponent.java:412)
        at org.jitsi.jicofo.xmpp.FocusComponent.handleIQSet(FocusComponent.java:248)
        at org.xmpp.component.AbstractComponent.processIQRequest(AbstractComponent.java:515)
        at org.xmpp.component.AbstractComponent.processIQ(AbstractComponent.java:289)
        at org.xmpp.component.AbstractComponent.processQueuedPacket(AbstractComponent.java:239)
        at org.xmpp.component.AbstractComponent.access$100(AbstractComponent.java:81)
        at org.xmpp.component.AbstractComponent$PacketProcessor.run(AbstractComponent.java:1051)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: forbidden(-1) Only owners can configure rooms
        at org.jivesoftware.smackx.muc.MultiUserChat.getConfigurationForm(MultiUserChat.java:577)
        at org.jitsi.impl.protocol.xmpp.ChatRoomImpl.joinAs(ChatRoomImpl.java:193)
        ... 15 more

**Comment by bgrozev** [comment]
outdated
