### ISSUE TITLE
Please update HttpClient from v4.4 to v4.4.1

### ISSUE THREAD

**Issue by kheir95** [jitsi/jicofo#380]
## Description
Version 4.4 of HttpClient has a bug filed in the following issue:
https://issues.apache.org/jira/browse/HTTPCLIENT-1610

It's causing a problem in Jicofo's reservation system showing an error message and requiring a refresh of the room in order for the connection to the REST API to succeed.
I described the bug in detail in the following blog post:
https://community.jitsi.org/t/jicofo-reservation-system-over-rest-api-error-at-every-start/19260

Jicofo threw the following exception when the bug appeared:

> Jicofo 2019-08-26 20:38:10.713 INFO: [66] org.jitsi.jicofo.xmpp.FocusComponent.handleConferenceIq().402 Focus request for room: test2234325324@muc.meet.jitsi
Jicofo 2019-08-26 20:38:10.714 INFO: [66] org.jitsi.impl.reservation.rest.ApiHandler.createNewConference().124 Sending post: {name=test2234325324, start_time=2019-08-26T20:38:10.713+02, duration=-1}
Jicofo 2019-08-26 20:38:10.716 SEVERE: [66] org.jitsi.impl.reservation.rest.RESTReservations.createConference().193 org.apache.http.NoHttpResponseException: 172.24.222.220:3000 failed to respond
org.apache.http.NoHttpResponseException: 172.24.222.220:3000 failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.jitsi.impl.reservation.rest.ApiHandler.createNewConference(ApiHandler.java:130)
	at org.jitsi.impl.reservation.rest.RESTReservations.createConference(RESTReservations.java:141)
	at org.jitsi.jicofo.xmpp.FocusComponent.processExtensions(FocusComponent.java:380)
	at org.jitsi.jicofo.xmpp.FocusComponent.handleConferenceIq(FocusComponent.java:415)
	at org.jitsi.jicofo.xmpp.FocusComponent.handleIQSetImpl(FocusComponent.java:260)
	at org.jitsi.xmpp.component.ComponentBase.handleIQSet(ComponentBase.java:362)
	at org.xmpp.component.AbstractComponent.processIQRequest(AbstractComponent.java:515)
	at org.xmpp.component.AbstractComponent.processIQ(AbstractComponent.java:289)
	at org.xmpp.component.AbstractComponent.processQueuedPacket(AbstractComponent.java:239)
	at org.xmpp.component.AbstractComponent.access$100(AbstractComponent.java:81)
	at org.xmpp.component.AbstractComponent$PacketProcessor.run(AbstractComponent.java:1051)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Jicofo 2019-08-26 20:38:10.716 INFO: [66] org.jitsi.jicofo.xmpp.FocusComponent.processExtensions().382 Create room result: Result[c=100, msg=172.24.222.220:3000 failed to respond]@808949186 for test2234325324@muc.meet.jitsi

## Solution
So I replaced the HttpClient jar file from v4.4 to v4.4.1 in the docker container (The one from docker-jitsi-meet) and the problem doesn't appear anymore. I ran all the scenarios explained in my post and now everything is working as it should be.

**Comment by bgrozev** [comment]
Can you open a PR?

**Comment by kheir95** [comment]
I'm actually not working privately on this and it's not legally straightforward on our side to contribute with  this.
Could someone who is already a contributor fix it?
