### ISSUE TITLE
Please use SRV record or document how to change c2s port

### ISSUE THREAD

**Issue by ivucica** [jitsi/jicofo#412]
Readme says:

> Jicofo uses an XMPP user connection (on port 5222 by default)

How does this get changed? My experimental XMPP server is not running on 5222 (as there's already another server running on it). The domain's `SRV` record in DNS is configured to point c2s connections to the alternative port. Other clients connect correctly.

Is not using `SRV` records expected?

Can you document the expected way to change the port? I have a feeling `org.jitsi.jicofo.auth.URL=XMPP:here.is.my.domain` is related in the `sip-communicator.properties`, but I don't see an obvious source of documentation. Maybe `README.md` would be a good place to mention this?

Also, `_xmpp-client._tcp` SRV record for `here.is.my.domain` could be used ;-)

**Comment by ver-luisant** [comment]
Hello,

I second comment from @ivucica .
My XMPP server does not use port 5222.

Port 5222 seems hardcoded here:
https://github.com/jitsi/jicofo/blob/master/src/main/java/org/jitsi/impl/protocol/xmpp/XmppProtocolProvider.java#L207

Adding a new setting in `config`  could be a good place to change the port.

`jicofo` log shows:
`Jicofo 2020-04-08 06:08:02.170 GRAVE: [18] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.doConnect().315 Failed to connect/login: The following addresses failed: 'localhost:5222' failed because: localhost/127.0.0.1 exception: java.net.ConnectException: Connexion refusée (Connection refused), localhost/0:0:0:0:0:0:0:1 exception: java.net.ConnectException: Connexion refusée (Connection refused)
org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'localhost:5222' failed because: localhost/127.0.0.1 exception: java.net.ConnectException: Connexion refusée (Connection refused), localhost/0:0:0:0:0:0:0:1 exception: java.net.ConnectException: Connexion refusée (Connection refused)
        at org.jivesoftware.smack.SmackException$ConnectionException.from(SmackException.java:278)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:619)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:902)
        at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:383)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.doConnect(XmppProtocolProvider.java:270)
        at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
`

Thanks for your support.
