### ISSUE TITLE
.ComponentMain.call().278 java.net.ConnectException: Connection refused

### ISSUE THREAD

**Issue by cheenwe** [jitsi/jicofo#80]
when i run  "./jicofo-linux-x64-1.0-SNAPSHOT/jicofo.sh --domain=2.61.25.227 --secret=jicofo_password --user_domain=auth.182.61.25.227 --user_name=focus --user_password=auth_password"

Jicofo 2016-04-29 16:26:43.058 SEVERE: [30] org.jitsi.meet.ComponentMain.call().278 java.net.ConnectException: Connection refused, host:xx.xxx.xx.xx, port:5347
org.xmpp.component.ComponentException: java.net.ConnectException: Connection refused
        at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:272)
        at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:221)
        at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:201)
        at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:270)
        at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:255)
        at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:151)
        ... 12 more

Jicofo 2016-04-29 16:26:43.913 INFO: [15] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.info() XMPP reconnection successful
Jicofo 2016-04-29 16:26:43.913 SEVERE: [15] org.jitsi.jicofo.ProtocolProviderHandler.registrationStateChanged().142 null
java.lang.NullPointerException
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.discoverItems(XmppProtocolProvider.java:499)
        at org.jitsi.impl.protocol.xmpp.OpSetSimpleCapsImpl.getItems(OpSetSimpleCapsImpl.java:53)
        at org.jitsi.jicofo.ComponentsDiscovery.discoverServices(ComponentsDiscovery.java:238)
        at org.jitsi.jicofo.ComponentsDiscovery.firstTimeDiscovery(ComponentsDiscovery.java:308)
        at org.jitsi.jicofo.ComponentsDiscovery.registrationStateChanged(ComponentsDiscovery.java:343)
        at org.jitsi.jicofo.ProtocolProviderHandler.registrationStateChanged(ProtocolProviderHandler.java:138)
        at net.java.sip.communicator.service.protocol.AbstractProtocolProviderService.fireRegistrationStateChanged(AbstractProtocolProviderService.java:187)
        at net.java.sip.communicator.service.protocol.AbstractProtocolProviderService.fireRegistrationStateChanged(AbstractProtocolProviderService.java:141)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.notifyConnected(XmppProtocolProvider.java:265)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.access$300(XmppProtocolProvider.java:49)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider$XmppConnectionListener.reconnectionSuccessful(XmppProtocolProvider.java:580)
        at org.jivesoftware.smack.PacketReader.notifyReconnection(PacketReader.java:193)
        at org.jivesoftware.smack.XMPPConnection.initConnection(XMPPConnection.java:589)
        at org.jivesoftware.smack.XMPPConnection.connectUsingConfiguration(XMPPConnection.java:532)
        at org.jivesoftware.smack.XMPPConnection.connect(XMPPConnection.java:968)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.doConnect(XmppProtocolProvider.java:220)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.access$000(XmppProtocolProvider.java:49)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider$1.call(XmppProtocolProvider.java:201)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider$1.call(XmppProtocolProvider.java:196)
        at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Jicofo 2016-04-29 16:26:43.916 INFO: [15] org.jitsi.jicofo.FocusManager.registrationStateChanged().531 XMPP provider reg state: RegistrationState=Registered
Jicofo 2016-04-29 16:26:43.925 SEVERE: [15] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.error() Failed to connect: SASL authentication DIGEST-MD5 failed: text
SASL authentication DIGEST-MD5 failed: text: 
        at org.jivesoftware.smack.SASLAuthentication.authenticate(SASLAuthentication.java:341)
        at org.jivesoftware.smack.XMPPConnection.login(XMPPConnection.java:208)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.doConnect(XmppProtocolProvider.java:233)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.access$000(XmppProtocolProvider.java:49)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider$1.call(XmppProtocolProvider.java:201)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider$1.call(XmppProtocolProvider.java:196)
        at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Jicofo 2016-04-29 16:26:48.031 SEVERE: [29] org.jitsi.xmpp.component.ComponentBase.run().370 Failed to send ping
java.lang.NullPointerException
        at org.xmpp.component.AbstractComponent.send(AbstractComponent.java:925)
        at org.jitsi.xmpp.component.ComponentBase.access$400(ComponentBase.java:34)
        at org.jitsi.xmpp.component.ComponentBase$PingTask.run(ComponentBase.java:358)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Jicofo 2016-04-29 16:26:48.062 SEVERE: [30] org.jitsi.meet.ComponentMain.call().278 java.net.ConnectException: Connection refused, host:xx.xxx.xx.xx, port:5347
org.xmpp.component.ComponentException: java.net.ConnectException: Connection refused
        at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:272)
        at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:221)
        at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:201)
        at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:270)
        at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:255)
        at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:151)
        ... 12 more
Jicofo 2016-04-29 16:26:49.020 INFO: [39] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.info() XMPP reconnection successful
Jicofo 2016-04-29 16:26:49.021 SEVERE: [39] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.error() Failed to connect: SASL authentication DIGEST-MD5 failed: text
SASL authentication DIGEST-MD5 failed: text: 
        at org.jivesoftware.smack.SASLAuthentication.authenticate(SASLAuthentication.java:341)
        at org.jivesoftware.smack.XMPPConnection.login(XMPPConnection.java:208)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.doConnect(XmppProtocolProvider.java:233)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.access$000(XmppProtocolProvider.java:49)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider$1.call(XmppProtocolProvider.java:201)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider$1.call(XmppProtocolProvider.java:196)
        at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Jicofo 2016-04-29 16:26:53.066 SEVERE: [30] org.jitsi.meet.ComponentMain.call().278 java.net.ConnectException: Connection refused, host:xx.xxx.xx.xx, port:5347
org.xmpp.component.ComponentException: java.net.ConnectException: Connection refused
        at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:272)
        at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:221)
        at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:201)
        at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:270)
        at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:255)
        at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:151)
        ... 12 more
Jicofo 2016-04-29 16:26:54.125 INFO: [34] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.info() XMPP reconnection successful
Jicofo 2016-04-29 16:26:54.125 SEVERE: [34] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.error() Failed to connect: SASL authentication DIGEST-MD5 failed: text
SASL authentication DIGEST-MD5 failed: text: 
        at org.jivesoftware.smack.SASLAuthentication.authenticate(SASLAuthentication.java:341)
        at org.jivesoftware.smack.XMPPConnection.login(XMPPConnection.java:208)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.doConnect(XmppProtocolProvider.java:233)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.access$000(XmppProtocolProvider.java:49)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider$1.call(XmppProtocolProvider.java:201)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider$1.call(XmppProtocolProvider.java:196)
        at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Jicofo 2016-04-29 16:26:54.136 SEVERE: [46] org.jivesoftware.smack.PacketWriter.writePackets() Error writing packet
java.io.IOException: Stream closed
        at java.io.BufferedWriter.ensureOpen(BufferedWriter.java:116)
        at java.io.BufferedWriter.write(BufferedWriter.java:221)
        at java.io.Writer.write(Writer.java:157)
        at org.jivesoftware.smack.PacketWriter.writePackets(PacketWriter.java:210)
        at org.jivesoftware.smack.PacketWriter.access$000(PacketWriter.java:42)
        at org.jivesoftware.smack.PacketWriter$1.run(PacketWriter.java:80)
Jicofo 2016-04-29 16:26:54.136 SEVERE: [56] org.jivesoftware.smack.PacketWriter.writePackets() Error writing packet
java.io.IOException: Stream closed
        at java.io.BufferedWriter.ensureOpen(BufferedWriter.java:116)
        at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:126)
        at java.io.BufferedWriter.flush(BufferedWriter.java:253)
        at org.jivesoftware.smack.PacketWriter.writePackets(PacketWriter.java:212)
        at org.jivesoftware.smack.PacketWriter.access$000(PacketWriter.java:42)
        at org.jivesoftware.smack.PacketWriter$1.run(PacketWriter.java:80)
Jicofo 2016-04-29 16:26:54.285 SEVERE: [57] org.jivesoftware.smack.PacketReader.notifyConnectionError() Closes the connection temporary
java.net.SocketException: Socket closed
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:152)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:442)
        at sun.security.ssl.InputRecord.read(InputRecord.java:480)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:934)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:891)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:102)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:154)
        at java.io.BufferedReader.read1(BufferedReader.java:205)
        at java.io.BufferedReader.read(BufferedReader.java:279)
        at org.xmlpull.mxp1.MXParser.fillBuf(MXParser.java:2992)
        at org.xmlpull.mxp1.MXParser.more(MXParser.java:3046)
        at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1144)
        at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)
        at org.jivesoftware.smack.PacketReader.parsePackets(PacketReader.java:329)
        at org.jivesoftware.smack.PacketReader.access$000(PacketReader.java:45)
        at org.jivesoftware.smack.PacketReader$1.run(PacketReader.java:74)
Jicofo 2016-04-29 16:26:54.287 SEVERE: [57] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.error() XMPP connection closed on error: Socket closed
Jicofo 2016-04-29 16:26:54.287 INFO: [57] org.jitsi.jicofo.FocusManager.registrationStateChanged().531 XMPP provider reg state: RegistrationState=Unregistered

**Comment by cheenwe** [comment]
#java -version
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

**Comment by damencho** [comment]
Please use the mailinglist before opening new issues!

Jicofo cannot connect to your xmpp server.
Connection refused, host:xx.xxx.xx.xx, port:5347. It tries to connect to host xx.xxx.xx.xx and the default port for connecting components 5347. It can be firewall issue, or your xmpp server is not configured to listen there.

**Comment by bgrozev** [comment]
Prosody might be restricted to listed on a specific interface (which can be configured with [http://prosody.im/doc/components](component_interface)).
