### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by filwu8** [jitsi/jicofo#953]
whe i try to use it inside jitsi i’have a lot of issues,how to fix ?

Jicofo 2022-08-10 19:18:25.747 INFO: [130] [room=%e6%a0%bc%e7%95%8c%e4%ba%91%e8%a7%86%e5%bc%80%e5%8f%91@muc.meet.jitsi meeting_id=31958ea7-f668-4d86-ac25-53e1b7e155c3] TranscriberManager.selectTranscriber#182: Attempting to invite transcriber
Jicofo 2022-08-10 19:18:25.747 SEVERE: [130] Main.lambda$main$0#52: An uncaught exception occurred in thread=Thread[pool-13-thread-2,5,main]
java.lang.NullPointerException
        at org.jitsi.jicofo.jigasi.TranscriberManager.selectTranscriber(TranscriberManager.java:184)
        at org.jitsi.jicofo.jigasi.TranscriberManager.startTranscribing(TranscriberManager.java:166)
        at org.jitsi.jicofo.jigasi.TranscriberManager.lambda$memberPresenceChanged$0(TranscriberManager.java:138)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by bgrozev** [comment]
You need to configure jigasi in `jicofo.conf` (see https://github.com/jitsi/jicofo/blob/master/src/main/resources/reference.conf#L279).

It's not great behavior, I'll look at improving it.
