### ISSUE TITLE
Race condition on startup leads to NPEs and failed requests

### ISSUE THREAD

**Issue by jbg** [jitsi/jicofo#957]
## Description
---
In `main()`, `JicofoServices` is set up [like this](https://github.com/jitsi/jicofo/blob/4782dcacef6a7507af1e9d1933e9d69eb37f60da/src/main/java/org/jitsi/jicofo/Main.java#L68):

```java
JicofoServices jicofoServices = new JicofoServices();
JicofoServices.jicofoServicesSingleton = jicofoServices;
```

`new JicofoServices()` seems to set up most of Jicofo's services, via all the initializers in the [`JicofoServices` class](https://github.com/jitsi/jicofo/blob/11040cfca0d735e961cfb6b3fdc2f3479826914c/src/main/kotlin/org/jitsi/jicofo/JicofoServices.kt#L61).

Once the `JicofoServices` object is constructed, Jicofo is already starting its HTTP server, trying to connect to XMPP, etc. Meanwhile the `JicofoServices.jicofoServicesSingleton` hasn't been set yet. This sets up a race condition where if those services can start up and receive incoming traffic fast enough, they may find that `JicofoServices.jicofoServicesSingleton` is still `null` while handling that traffic.

If we restart Jicofo during a load test (simulating e.g. an unplanned restart and subsequent recovery under load), we see a series of these in the logs just after startup:

```
SEVERE An uncaught exception occurred in thread=Thread[Jicofo Global IO Poolpool-2-thread-2,5,main]
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at org.jitsi.jicofo.conference.JitsiMeetConferenceImpl.<init>(JitsiMeetConferenceImpl.java:250)
	at org.jitsi.jicofo.FocusManager.createConference(FocusManager.java:254)
	at org.jitsi.jicofo.FocusManager.conferenceRequest(FocusManager.java:200)
	at org.jitsi.jicofo.FocusManager.conferenceRequest(FocusManager.java:162)
	at org.jitsi.jicofo.FocusManager.conferenceRequest(FocusManager.java:141)
	at org.jitsi.jicofo.xmpp.ConferenceIqHandler.handleConferenceIq(ConferenceIqHandler.kt:72)
	at org.jitsi.jicofo.xmpp.ConferenceIqHandler.handleIQRequest$lambda-4(ConferenceIqHandler.kt:156)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

In this case it's caused by Jicofo managing to connect to XMPP and receive an IQ between the execution of the two lines of code above. You can imagine similar issues might be caused by traffic to other services e.g. an HTTP request or health check.

This is not only reproducible under synthetic load — we started debugging it after getting alerted to one of these stack traces in production.

## Current behavior
---
NPEs if requests come in very soon after startup.

## Expected Behavior
---
No NPEs.

## Possible Solution
---
One option would be to clean up `JicofoServices` to not do work in the initializers (maybe have a `start()` method that could be called after the singleton is set).

## Steps to reproduce
---
Generate some heavy signalling load (e.g. create conferences in a loop) and then restart Jicofo under load.

# Environment details
---
Built from source, running on Java 17 in a container (k8s pod) on linux/arm64. Reproducible on latest Git master.

**Comment by bgrozev** [comment]
Since you have a way to repro, can you please check if #959 fixes the problem?

**Comment by jbg** [comment]
I'm unable to reproduce the issue after applying #959.
